#!/bin/bash

API_URL="https://pokeapi.co/api/v2/pokemon/pikachu"
OUTPUT_FILE="data.json"
ERROR_FILE="errors.txt"

curl -s -f "$API_URL" -o "$OUTPUT_FILE" 2>>"$ERROR_FILE"
if [ $? -ne 0 ]; then
    echo "Failed to fetch data for Pikachu from $API_URL" >> "$ERROR_FILE"
fi


#to run the script
#sudo apt-get install dos2unix
#dos2unix apiAutomation-0x00
#chmod +x apiAutomation-0x00
#./apiAutomation-0x00